language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.0
    - android-27
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

jdk:
  - oraclejdk8

before_install:
- echo "sdk.dir=$ANDROID_HOME" > local.properties
- mkdir -p "${ANDROID_HOME}/licenses"
- echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"

branches:
  except:
    - gh-pages

script: ./gradlew clean build testDebugUnitTest