language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.0
    - android-27
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

jdk:
  - oraclejdk8

before_install:
- echo "sdk.dir=$ANDROID_HOME" > local.properties

branches:
  except:
    - gh-pages

script: ./gradlew clean build testDebugUnitTest